"""add profile fields to gw_user (US-011)

Revision ID: 0f282d3d2219
Revises: 837c9d1f23456
Create Date: 2026-02-21 10:06:48.693380

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0f282d3d2219"
down_revision = "837c9d1f23456"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gw_user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("display_name", sa.String(length=80), nullable=True)
        )
        batch_op.add_column(
            sa.Column("avatar_url", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("bio", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "language_preference",
                sa.String(length=5),
                nullable=False,
                server_default="en",
            )
        )
        batch_op.add_column(
            sa.Column(
                "timezone",
                sa.String(length=50),
                nullable=False,
                server_default="UTC",
            )
        )
        batch_op.add_column(
            sa.Column("profile_updated_at", sa.DateTime(), nullable=True)
        )

    with op.batch_alter_table("refresh_token", schema=None) as batch_op:
        batch_op.drop_index("ix_refresh_token_family_id")
        batch_op.drop_index("ix_refresh_token_token")
        batch_op.drop_index("ix_refresh_token_user_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refresh_token", schema=None) as batch_op:
        batch_op.create_index(
            "ix_refresh_token_user_id", ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_refresh_token_token", ["token"], unique=False
        )
        batch_op.create_index(
            "ix_refresh_token_family_id", ["family_id"], unique=False
        )

    with op.batch_alter_table("gw_user", schema=None) as batch_op:
        batch_op.drop_column("profile_updated_at")
        batch_op.drop_column("timezone")
        batch_op.drop_column("language_preference")
        batch_op.drop_column("bio")
        batch_op.drop_column("avatar_url")
        batch_op.drop_column("display_name")

    # ### end Alembic commands ###
