"""initial migrations

Revision ID: 835da9b57698
Revises:
Create Date: 2025-07-17 17:56:46.127310

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "835da9b57698"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gw_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=80), nullable=False),
        sa.Column("password", sa.String(length=500), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column(
            "last_activation_token", sa.String(length=100), nullable=True
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("activated_on", sa.DateTime(), nullable=True),
        sa.Column("deactivated_on", sa.DateTime(), nullable=True),
        sa.Column("jwt_session_id", sa.String(length=500), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
        comment="Define the properties of the user.",
    )
    op.create_table(
        "stats_api_endpoints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("endpoint_url", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint_url"),
        comment="Define the statistic for the calls of endpoints.",
    )
    op.create_table(
        "gw_user_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("gwuser_id", sa.UUID(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gwuser_id"],
            ["gw_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Define the role of the user.",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gw_user_role")
    op.drop_table("stats_api_endpoints")
    op.drop_table("gw_user")
    # ### end Alembic commands ###
