services:
  iam_gateway_container_dev:
    build: ../../../
    command: python -m flask --app application run -h 0.0.0.0
    container_name: iam_gateway_container_dev
    image: "${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:${APP_NAME}-${APP_ENV}-${APP_VERSION}"
    ports:
      - 5011:5000
    env_file:
      - .env
      - app.version.env
      - app.name.env
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: iam_gateway_redis_dev
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
